Repository jupyter/nbformat, pull requests merged in 2022-04, with the labels that each got.

#257 Adopt pre-commit
  .pre-commit-config.yaml
  MANIFEST.in
  docs/format_description.rst
  setup.py
Labels: maintenance

#259 Add flake8 and git-blame-ignore-revs
  .git-blame-ignore-revs
  .github/scripts/parse_ref.py
  .pre-commit-config.yaml
  MANIFEST.in
  docs/conf.py
  nbformat/__init__.py
  nbformat/_compat.py
  nbformat/_struct.py
  nbformat/converter.py
  nbformat/corpus/tests/test_words.py
  nbformat/corpus/words.py
  nbformat/json_compat.py
  nbformat/sign.py
  nbformat/v1/nbbase.py
  nbformat/v2/convert.py
  nbformat/v2/nbbase.py
  nbformat/v2/rwbase.py
  nbformat/v3/convert.py
  nbformat/v3/nbbase.py
  nbformat/v3/nbjson.py
  nbformat/v3/rwbase.py
  nbformat/v4/convert.py
  nbformat/v4/rwbase.py
  nbformat/validator.py
  setup.cfg
  tests/base.py
  tests/test_validator.py
  tests/v1/nbexamples.py
  tests/v1/test_nbbase.py
  tests/v2/nbexamples.py
  tests/v2/test_json.py
  tests/v2/test_nbpy.py
  tests/v3/formattest.py
  tests/v3/nbexamples.py
  tests/v3/test_json.py
  tests/v3/test_nbpy.py
  tests/v4/formattest.py
  tests/v4/nbexamples.py
  tests/v4/test_convert.py
  tests/v4/test_json.py
  tests/v4/test_nbbase.py
  tests/v4/test_validate.py
Labels: maintenance

#260 Add pyproject.toml file and configure pytest
  .github/workflows/tests.yml
  docs/changelog.rst
  docs/markup.rst
  docs/requirements.txt
  pyproject.toml
Labels: maintenance

#262 Use fastjsonschema by default
  nbformat/json_compat.py
  nbformat/validator.py
  setup.py
Labels: enhancement

#263 Update validator docs
  README.md
  docs/api.rst
Labels: docs

#264 Update changelog for 5.3
  docs/changelog.rst
Labels: docs

#269 Fix import nbformat.current
  nbformat/current.py
Labels: bug

#268 Clean up pre-commit
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
Labels: maintenance

#270 Add mypy support
  .pre-commit-config.yaml
  docs/conf.py
  nbformat/current.py
  nbformat/notebooknode.py
  nbformat/py.typed
  nbformat/sign.py
  nbformat/v2/nbpy.py
  nbformat/v3/nbpy.py
  nbformat/v4/convert.py
  nbformat/v4/nbbase.py
  nbformat/validator.py
  pyproject.toml
  setup.py
  tests/test_api.py
  tests/test_sign.py
  tests/v3/formattest.py
  tests/v4/formattest.py
Labels: maintenance

#271 Improve CI
  .github/workflows/tests.yml
  nbformat/sign.py
  setup.py
Labels: maintenance
