Repository jupyter/nbformat, pull requests merged in 2023-07, with the labels that each got.

#368 Fix deprecation warning when importing from jsonschema
  nbformat/json_compat.py
Labels: maintenance

#370 Update link to notebook security
  docs/api.rst
  docs/conf.py
Labels: documentation, maintenance

#372 Fix version handling
  .github/workflows/tests.yml
  nbformat/_version.py
  pyproject.toml
Labels: bug

#371 Fix encoding warnings
  nbformat/sign.py
  nbformat/validator.py
  pyproject.toml
  tests/test_sign.py
  tests/v4/test_json.py
Labels: maintenance
