Repository jupyter/nbformat, pull requests merged in 2023-01, with the labels that each got.

#342 Only require nbformat_minor for v4
  nbformat/v4/convert.py
  tests/test3_no_min_version.ipynb
  tests/test_validator.py
Labels: bug

#343 Undeprecate validate(nb, relax_add_props=True)
  nbformat/validator.py
Labels: maintenance

#344 Only add ellipsis to NotJSONError message if message is truncated
  nbformat/reader.py
Labels: maintenance

#345 Add more linting
  .github/scripts/parse_ref.py
  .pre-commit-config.yaml
  docs/conf.py
  nbformat/__init__.py
  nbformat/_imports.py
  nbformat/_struct.py
  nbformat/converter.py
  nbformat/corpus/tests/test_words.py
  nbformat/current.py
  nbformat/json_compat.py
  nbformat/notebooknode.py
  nbformat/reader.py
  nbformat/sign.py
  nbformat/v1/convert.py
  nbformat/v1/nbbase.py
  nbformat/v1/rwbase.py
  nbformat/v2/__init__.py
  nbformat/v2/convert.py
  nbformat/v2/nbbase.py
  nbformat/v2/nbpy.py
  nbformat/v2/rwbase.py
  nbformat/v3/__init__.py
  nbformat/v3/convert.py
  nbformat/v3/nbbase.py
  nbformat/v3/nbpy.py
  nbformat/v3/rwbase.py
  nbformat/v4/__init__.py
  nbformat/v4/convert.py
  nbformat/v4/nbbase.py
  nbformat/v4/nbjson.py
  nbformat/v4/rwbase.py
  nbformat/validator.py
  pyproject.toml
  tests/base.py
  tests/test_nbformat.py
  tests/test_reader.py
  tests/test_validator.py
  tests/v3/formattest.py
  tests/v3/test_misc.py
  tests/v4/formattest.py
  tests/v4/test_convert.py
Labels: maintenance

#346 DOC: README: capitalization, title
  README.md
Labels: documentation
